class _object:
	...
class _void:
	...
class _Bins:
	...
class _CacheManager:
	...
class _MenuManager:
	...
class _File:
	...
class _TimeStamp:
	...
class _LookUpTable3D:
	...
class _MtlData3D:
	...
class _Tag:
	...
class _ScriptValType:
	...
class _ViewShadeNodeGroup:
	...

object = _object
void = _void
Bins = _Bins
CacheManager = _CacheManager
MenuManager = _MenuManager
File = _File
TimeStamp = _TimeStamp
LookUpTable3D = _LookUpTable3D
MtlData3D = _MtlData3D
Tag = _Tag
ScriptValType = _ScriptValType
ViewShadeNodeGroup = _ViewShadeNodeGroup

