from Request import _Request
from Image import _Image
from _non_existing import _void


class _DVIPComputeNode:

	#---Methods---#
	def SetParamStructCopy(self, params: _void, size: int) -> None:
		...
	def info_text(self):
		...
	def GetErrorLog(self) -> str:
		...
	def SetWorkSize(self, w: int, h: int, d: int) -> None:
		...
	def GetKernelName(self) -> str:
		...
	def AddSampler(self, name: str, filterMode: int, addressMode: int, normCoordsMode: int) -> None:
		...
	def DVIPComputeNode(self, req: _Request, kernelName: str, source: str, kernelParamsName: str, kernelParams: str) -> _DVIPComputeNode:
		"""
		DVIPComputeNode constructor
		"""
		...
	def AddInput(self, name: str, img: _Image) -> None:
		...
	def GetParamsHash(self, paramStr: str) -> int:
		...
	def AddOutput(self, name: str, img: _Image) -> None:
		...
	def RunSession(self, req: _Request) -> bool:
		...
	def header_text(self):
		...
	def GetKernelParams(self) -> str:
		...
	def SetGlobalSize(self, w: int, h: int, d: int) -> None:
		...
	def ForceRebuild(self) -> None:
		...

DVIPComputeNode = _DVIPComputeNode