from FuPath FuPathstring str import _FuPath FuPathstring str


class _FuPath:

	#---Methods---#
	def FuPath(self) -> _FuPath FuPathstring str:
		"""
		FuPath constructor
		"""
		...
	def RemoveSegment(self, seg: int) -> bool:
		...
	def IsFile(self, str: str) -> bool:
		...
	def IsDir(self, str: str) -> bool:
		...
	def GetSegment(self, seg: int) -> str:
		...
	def AddSegment(self, str: str, skipDupes: bool) -> bool:
		...
	def SetSegment(self, seg: int, str: str) -> bool:
		...
	def info_text(self):
		...
	def GetAllSegments(self) -> str:
		...
	def GetFirstMatch(self, str: str) -> str:
		...
	def GetClosestMatch(self, str: str) -> str:
		...
	def Exists(self, str: str) -> bool:
		...
	def GetNumSegments(self) -> int:
		...
	def header_text(self):
		...

FuPath = _FuPath