class _FusionUI:

	#---Attributes---#
	REGS_VersionString: str

	REGI_Version: int

	REGB_Hide: bool

	REGB_SupportsDoD: bool

	REGI_ClassType: int

	REGI_Priority: int

	REGS_ID: str

	REGS_Name: str

	REGB_Unpredictable: bool

	REGB_ControlView: bool


	#---Methods---#
	def SetActiveWndIndex(self):
		...
	def SetActiveFrameIndex(self):
		...
	def RequestDir(self) -> None:
		...
	def AskQuit(self) -> None:
		"""
		Quit Fusion
		"""
		...
	def ShowHelp(self):
		...
	def CustomizeHotkeys(self):
		...
	def GetWndNameIndex(self):
		...
	def GetFrameNameIndex(self):
		...
	def GetMouseButtons(self):
		...
	def GetModifiers(self):
		...
	def header_text(self):
		...
	def _Output_Print(self):
		...
	def _Output_Error(self):
		...
	def _MasterApp_Active(self) -> None:
		...
	def ShowUI(self):
		...
	def ShowMenu(self) -> None:
		...
	def ShowConsole(self):
		...
	def ShowActions(self) -> None:
		...
	def GetActiveFrameIndex(self):
		...
	def GetActiveWndIndex(self):
		...
	def NewScript(self) -> None:
		"""
		New Script
		"""
		...
	def SetUILayout(self):
		...
	def GetUILayout(self):
		...
	def IsConsoleShowing(self):
		...
	def CustomizeToolbars(self):
		...
	def RequestFile(self) -> None:
		...
	def IsUIVisible(self):
		...

FusionUI = _FusionUI