from Tag import _Tag
from RefObject import _RefObject
from TagList import _TagList
from void import _void


class _RefObject:

	#---Properties---#
	UseCount: int
	"""
	Read Only
	"""

	#---Methods---#
	def _GetAttr_String(self, tag: _Tag, def: str) -> str:
		...
	def _GetAttr_ID(self, tag: _Tag, def: str) -> str:
		...
	def _GetAttr_bool(self, tag: _Tag, def: bool) -> bool:
		...
	def _GetAttr_Object(self, tag: _Tag, def: _RefObject) -> _RefObject:
		...
	def _GetAttr_TagList(self, tag: _Tag, def: _TagList) -> _TagList:
		...
	def header_text(self):
		...
	def info_text(self):
		...
	def IncRef(self) -> None:
		...
	def DecRef(self) -> None:
		...
	def SetAttrsTagList(self, tags: _TagList) -> bool:
		...
	def _GetAttr_int32(self, tag: _Tag, def: int) -> int:
		...
	def _GetAttr_uint32(self, tag: _Tag, def: int) -> int:
		...
	def _GetAttr_float64(self, tag: _Tag, def: float) -> float:
		...
	def _GetAttr_Ptr(self, tag: _Tag, def: _void) -> None:
		...

RefObject = _RefObject