from Parameter import _Parameter
from TimeExtent import _TimeExtent
from Input import _Input
from TagList import _TagList
from ImageDomain import _ImageDomain
from Operator import _Operator
from Output import _Output
from _non_existing import _TimeStamp


class _Request:

	#---Properties---#
	BaseTime: float
	"""
	Read Only
	"""
	SourceImg: _Parameter
	"""
	Read Only
	"""
	SourceImgValid: _TimeExtent
	"""
	Read Only
	"""
	Time: float
	"""
	Read Only
	"""

	#---Attributes---#
	REGS_VersionString: str

	REGI_Version: int

	REGB_Hide: bool

	REGB_SupportsDoD: bool

	REGI_ClassType: int

	REGI_Priority: int

	REGS_ID: str

	REGS_Name: str

	REGB_Unpredictable: bool

	REGB_ControlView: bool


	#---Methods---#
	def SetAllOutputsCurrent(self, current: bool) -> bool:
		...
	def SetInputAttrs(self, inp: _Input, tags: _TagList, slot: int) -> bool:
		...
	def SetInputBaseTime(self, inp: _Input, t: _TimeStamp, slot: int) -> bool:
		...
	def SetInputCurrent(self, inp: _Input, current: bool, slot: int) -> bool:
		...
	def SetInputData(self, inp: _Input, param: _Parameter, te: _TimeExtent, slot: int, flags: int) -> bool:
		...
	def SetInputFlags(self, inp: _Input, flags: int, slot: int) -> bool:
		...
	def Lock(self) -> None:
		...
	def ClearInputData(self, inp: _Input, slot: int) -> bool:
		...
	def ClearInputFlags(self, inp: _Input, flags: int, slot: int) -> bool:
		...
	def ClearReqFlags(self, flags: int) -> None:
		...
	def FreeAllInputs(self) -> None:
		...
	def FreeAllOutputs(self) -> None:
		...
	def GetBaseTime(self) -> float:
		...
	def GetDoD(self) -> _ImageDomain:
		...
	def GetInputAttrs(self, inp: _Input, slot: int) -> _TagList:
		...
	def GetFlags(self) -> int:
		...
	def GetInputBaseTime(self, inp: _Input, slot: int) -> _TimeStamp:
		...
	def GetInputData(self, inp: _Input, slot: int) -> _Parameter:
		...
	def GetInputDataValid(self, inp: _Input, slot: int) -> _TimeExtent:
		...
	def GetInputDoD(self, inp: _Input, slot: int) -> _ImageDomain:
		...
	def GetInputFlags(self, inp: _Input, slot: int) -> int:
		...
	def GetInputRoI(self, inp: _Input, slot: int) -> _ImageDomain:
		...
	def GetInputTime(self, inp: _Input, slot: int) -> _TimeStamp:
		...
	def GetOp(self) -> _Operator:
		...
	def GetOutputData(self, out: _Output) -> _Parameter:
		...
	def GetOutputDataValid(self, out: _Output) -> _TimeExtent:
		...
	def GetPending(self) -> int:
		...
	def GetPri(self) -> int:
		...
	def GetRoI(self) -> _ImageDomain:
		...
	def header_text(self):
		...
	def GetTime(self) -> float:
		...
	def IsCompleted(self) -> bool:
		...
	def IsFailed(self) -> bool:
		...
	def IsInputCurrent(self, inp: _Input, slot: int) -> bool:
		...
	def IsInputSet(self, inp: _Input, slot: int) -> bool:
		...
	def IsInteractive(self) -> bool:
		...
	def IsIntermediate(self) -> bool:
		...
	def IsNoCache(self) -> bool:
		...
	def SetOp(self, op: _Operator) -> bool:
		...
	def IsNoMotionBlur(self) -> bool:
		...
	def SetOutputCurrent(self, out: _Output, current: bool) -> bool:
		...
	def IsNoPreviewResize(self) -> bool:
		...
	def SetOutputData(self, out: _Output, param: _Parameter, te: _TimeExtent) -> bool:
		...
	def IsOutputCurrent(self, out: _Output) -> bool:
		...
	def SetPri(self, pri: int, pending: int) -> None:
		...
	def IsOutputSet(self, out: _Output) -> bool:
		...
	def IsPending(self) -> bool:
		...
	def SetReqAttrs(self, tags: _TagList) -> None:
		...
	def IsPlayback(self) -> bool:
		...
	def SetReqFlags(self, flags: int) -> None:
		...
	def IsPreCalc(self) -> bool:
		...
	def Unlock(self) -> None:
		...
	def IsPreview(self) -> bool:
		...
	def UnlockInputData(self, inp: _Input, slot: int) -> None:
		...
	def IsProcessing(self) -> bool:
		...
	def UnlockOutputData(self, out: _Output) -> None:
		...
	def IsQuick(self) -> bool:
		...
	def info_text(self):
		...
	def IsRemote(self) -> bool:
		...
	def IsSecondaryTime(self) -> bool:
		...
	def IsSerialised(self) -> bool:
		...
	def IsStampOnly(self) -> bool:
		...
	def LockInputData(self, inp: _Input, slot: int) -> None:
		...
	def IsQuiet(self) -> bool:
		...
	def LockOutputData(self, out: _Output) -> None:
		...
	def SetInputTime(self, inp: _Input, t: _TimeStamp, slot: int) -> bool:
		...

Request = _Request