from Tag import _Tag
from void import _void
from RefObject import _RefObject
from TagList import _TagList
from TagList TagList import _TagList TagList


class _TagList:

	#---Methods---#
	def _Get_float64(self, tag: _Tag, def: float) -> float:
		...
	def _Get_Ptr(self, tag: _Tag, def: _void) -> None:
		...
	def _Get_Object(self, tag: _Tag, def: _RefObject) -> _RefObject:
		...
	def _Get_TagList(self, tag: _Tag, def: _TagList) -> _TagList:
		...
	def TagList(self) -> _TagList TagList:
		"""
		TagList constructor
		"""
		...
	def header_text(self):
		...
	def info_text(self):
		...
	def _Set_int32(self, tag: _Tag, val: int, addnew: bool) -> None:
		...
	def _Set_uint32(self, tag: _Tag, val: int, addnew: bool) -> None:
		...
	def _Set_float64(self, tag: _Tag, val: float, addnew: bool) -> None:
		...
	def _Set_String(self, tag: _Tag, val: str, addnew: bool) -> None:
		...
	def _Set_ID(self, tag: _Tag, val: str, addnew: bool) -> None:
		...
	def _Set_Ptr(self, tag: _Tag, val: _void, addnew: bool) -> None:
		...
	def _Set_PtrRaw(self, tag: _Tag, val: _void, addnew: bool) -> None:
		...
	def _Set_Object(self, tag: _Tag, val: _RefObject, addnew: bool) -> None:
		...
	def _Set_TagList(self, tag: _Tag, val: _TagList, addnew: bool) -> None:
		...
	def _Get_ID(self, tag: _Tag, def: str) -> str:
		...
	def _Get_String(self, tag: _Tag, def: str) -> str:
		...
	def _Get_int32(self, tag: _Tag, def: int) -> int:
		...
	def _Get_uint32(self, tag: _Tag, def: int) -> int:
		...

TagList = _TagList