from typing import Literal

from Matrix4 import _Matrix4


class _Vector3f:

	#---Properties---#
	TypeName: str
	"""
	Read Only
	"""
	TypeNamePtr: str
	"""
	Read Only
	"""

	#---Methods---#
	def __div(self, num: float) -> _Vector3f:
		...
	def __pow(self, vec: _Vector3f) -> _Vector3f:
		...
	def __unm(self) -> _Vector3f:
		...
	def LengthSquared(self) -> float:
		...
	def IsNaN(self) -> bool:
		...
	def IsNormalized(self) -> bool:
		...
	def IsZero(self, num: float) -> bool:
		...
	def Equals(self, vec: _Vector3f) -> bool:
		...
	def header_text(self):
		...
	def info_text(self):
		...
	def _mulMat4(self, mat: _Matrix4) -> _Vector3f:
		...
	def _mulNum(self, num: float) -> _Vector3f:
		...
	def Length(self) -> float:
		...
	def __eq(self, vec: _Vector3f) -> bool:
		...
	def Normalize(self) -> None:
		...
	def _newVec3f(self, vec: _Vector3f) -> _Vector3f:
		...
	def _newNums(self, x: float, y: float, z: float) -> _Vector3f:
		...
	def Project(self, vec: _Vector3f) -> None:
		...
	def __add(self, vec: _Vector3f) -> _Vector3f:
		...
	def __sub(self, vec: _Vector3f) -> _Vector3f:
		...

Vector3f = _Vector3f