class FuPath_:

	#---Methods---#
	def info_text(self) -> None:
		...
	def AddSegment(self, str: str, skipDupes: bool) -> bool:
		...
	def SetSegment(self, seg: int, str: str) -> bool:
		...
	def RemoveSegment(self, seg: int) -> bool:
		...
	def GetAllSegments(self) -> str:
		...
	def GetFirstMatch(self, str: str) -> str:
		...
	def GetClosestMatch(self, str: str) -> str:
		...
	def Exists(self, str: str) -> bool:
		...
	def GetNumSegments(self) -> int:
		...
	def GetSegment(self, seg: int) -> str:
		...
	def header_text(self) -> None:
		...
	def IsFile(self, str: str) -> bool:
		...
	def IsDir(self, str: str) -> bool:
		...
	def FuPath(self, str: str) -> FuPath_:
		"""
		FuPath constructor
		"""
		...

FuPath = FuPath_