from ColorMatrix import _ColorMatrix


class _ColorMatrixFull:

	#---Properties---#
	TypeName: str
	"""
	Read Only
	"""
	TypeNamePtr: str
	"""
	Read Only
	"""

	#---Methods---#
	def IsIdentity(self) -> bool:
		...
	def Offset(self, r: float, g: float, b: float, a: float) -> None:
		...
	def RGBtoYUV(self) -> None:
		...
	def RotA(self, angle: float) -> None:
		...
	def RotB(self, angle: float) -> None:
		...
	def header_text(self):
		...
	def RotG(self, angle: float) -> None:
		...
	def Identity(self) -> None:
		...
	def RotR(self, angle: float) -> None:
		...
	def _newDef(self) -> _ColorMatrixFull:
		...
	def info_text(self):
		...
	def Determinant(self) -> float:
		...
	def Scale(self, r: float, g: float, b: float, a: float) -> None:
		...
	def _mulCMF(self, cm: _ColorMatrixFull) -> _ColorMatrixFull:
		...
	def __eq(self, cm: _ColorMatrixFull) -> bool:
		...
	def _newCMF(self, cm: _ColorMatrixFull) -> _ColorMatrixFull:
		...
	def _newCM(self, cm: _ColorMatrix) -> _ColorMatrixFull:
		...
	def _mulNum(self, num: float) -> _ColorMatrixFull:
		...
	def Inverse(self) -> _ColorMatrixFull:
		...
	def Adjoint(self) -> None:
		...
	def __add(self, cm: _ColorMatrixFull) -> _ColorMatrixFull:
		...
	def YUVtoRGB(self) -> None:
		...

ColorMatrixFull = _ColorMatrixFull