from ColorMatrix import ColorMatrix_


class ColorMatrixFull_:

	#---Properties---#
	TypeName: str
	"""
	Read Only
	"""
	TypeNamePtr: str
	"""
	Read Only
	"""

	#---Methods---#
	def IsIdentity(self) -> bool:
		...
	def Offset(self, r: float, g: float, b: float, a: float) -> None:
		...
	def RGBtoYUV(self) -> None:
		...
	def RotA(self, angle: float) -> None:
		...
	def RotB(self, angle: float) -> None:
		...
	def header_text(self) -> None:
		...
	def RotG(self, angle: float) -> None:
		...
	def Identity(self) -> None:
		...
	def RotR(self, angle: float) -> None:
		...
	def _newDef(self) -> ColorMatrixFull_:
		...
	def info_text(self) -> None:
		...
	def Determinant(self) -> float:
		...
	def Scale(self, r: float, g: float, b: float, a: float) -> None:
		...
	def _mulCMF(self, cm: ColorMatrixFull_) -> ColorMatrixFull_:
		...
	def __eq(self, cm: ColorMatrixFull_) -> bool:
		...
	def _newCMF(self, cm: ColorMatrixFull_) -> ColorMatrixFull_:
		...
	def _newCM(self, cm: ColorMatrix_) -> ColorMatrixFull_:
		...
	def _mulNum(self, num: float) -> ColorMatrixFull_:
		...
	def Inverse(self) -> ColorMatrixFull_:
		...
	def Adjoint(self) -> None:
		...
	def __add(self, cm: ColorMatrixFull_) -> ColorMatrixFull_:
		...
	def YUVtoRGB(self) -> None:
		...

ColorMatrixFull = ColorMatrixFull_