from Vector4 import Vector4_
from Vector3f import Vector3f_


class Matrix4_:

	#---Properties---#
	TypeName: str
	"""
	Read Only
	"""
	TypeNamePtr: str
	"""
	Read Only
	"""

	#---Methods---#
	def RotX(self, a: float) -> None:
		...
	def RotY(self, a: float) -> None:
		...
	def RotZ(self, a: float) -> None:
		...
	def LookAt(self, eye: Vector4_, at: Vector4_, up: Vector4_) -> None:
		...
	def _newNums(self, a11: float, a12: float, a13: float, a14: float, a21: float, a22: float, a23: float, a24: float, a31: float, a32: float, a33: float, a34: float, a41: float, a42: float, a43: float, a44: float) -> Matrix4_:
		...
	def _newMat4(self, mat: Matrix4_) -> Matrix4_:
		...
	def _newDef(self) -> Matrix4_:
		...
	def __mul(self, mat: Matrix4_) -> Matrix4_:
		...
	def _Ortho6(self, xmin: float, xmax: float, ymin: float, ymax: float, zmin: float, zmax: float) -> None:
		...
	def _Ortho3(self, width: float, height: float, depth: float) -> None:
		...
	def Adjoint(self) -> None:
		...
	def TransformPoint(self, out: Vector4_, inp: Vector4_) -> None:
		...
	def header_text(self) -> None:
		...
	def SetIdentity(self) -> None:
		...
	def Identity(self) -> None:
		...
	def SetZero(self) -> None:
		...
	def SetOne(self) -> None:
		...
	def info_text(self) -> None:
		...
	def Determinant(self) -> float:
		...
	def Move(self, x: float, y: float, z: float) -> None:
		...
	def Scale(self, x: float, y: float, z: float) -> None:
		...
	def Shear(self, x: float, y: float, z: float) -> None:
		...
	def RotAxis(self, xaxis: float, yaxis: float, zaxis: float, rad: float) -> None:
		...
	def Project(self, persp: float) -> None:
		...
	def Perspective(self, fovy: float, aspect: float, znear: float, zfar: float) -> None:
		...
	def ProjectWindow(self, width: float, height: float, znear: float, zfar: float) -> None:
		...
	def MapQuad(self, tlX: float, tlY: float, trX: float, trY: float, blX: float, blY: float, brX: float, brY: float) -> bool:
		...
	def Rotate(self, x: float, y: float, z: float, order: str) -> None:
		...
	def Inverse(self) -> Matrix4_:
		...
	def Transpose(self) -> Matrix4_:
		...
	def InverseTranspose(self) -> Matrix4_:
		...
	def TransformNormal(self, norm: Vector3f_) -> Vector3f_:
		...

Matrix4 = Matrix4_