from Parameter import Parameter_
from TimeExtent import TimeExtent_
from Input import Input_
from TagList import TagList_
from ImageDomain import ImageDomain_
from Operator import Operator_
from Output import Output_
from _non_existing import TimeStamp_


class Request_:

	#---Properties---#
	BaseTime: float
	"""
	Read Only
	"""
	SourceImg: Parameter_
	"""
	Read Only
	"""
	SourceImgValid: TimeExtent_
	"""
	Read Only
	"""
	Time: float
	"""
	Read Only
	"""

	#---Attributes---#
	REGS_VersionString: str

	REGI_Version: int

	REGB_Hide: bool

	REGB_SupportsDoD: bool

	REGI_ClassType: int

	REGI_Priority: int

	REGS_ID: str

	REGS_Name: str

	REGB_Unpredictable: bool

	REGB_ControlView: bool


	#---Methods---#
	def SetAllOutputsCurrent(self, current: bool) -> bool:
		...
	def SetInputAttrs(self, inp: Input_, tags: TagList_, slot: int) -> bool:
		...
	def SetInputBaseTime(self, inp: Input_, t: TimeStamp_, slot: int) -> bool:
		...
	def SetInputCurrent(self, inp: Input_, current: bool, slot: int) -> bool:
		...
	def SetInputData(self, inp: Input_, param: Parameter_, te: TimeExtent_, slot: int, flags: int) -> bool:
		...
	def SetInputFlags(self, inp: Input_, flags: int, slot: int) -> bool:
		...
	def Lock(self) -> None:
		...
	def ClearInputData(self, inp: Input_, slot: int) -> bool:
		...
	def ClearInputFlags(self, inp: Input_, flags: int, slot: int) -> bool:
		...
	def ClearReqFlags(self, flags: int) -> None:
		...
	def FreeAllInputs(self) -> None:
		...
	def FreeAllOutputs(self) -> None:
		...
	def GetBaseTime(self) -> float:
		...
	def GetDoD(self) -> ImageDomain_:
		...
	def GetInputAttrs(self, inp: Input_, slot: int) -> TagList_:
		...
	def GetFlags(self) -> int:
		...
	def GetInputBaseTime(self, inp: Input_, slot: int) -> TimeStamp_:
		...
	def GetInputData(self, inp: Input_, slot: int) -> Parameter_:
		...
	def GetInputDataValid(self, inp: Input_, slot: int) -> TimeExtent_:
		...
	def GetInputDoD(self, inp: Input_, slot: int) -> ImageDomain_:
		...
	def GetInputFlags(self, inp: Input_, slot: int) -> int:
		...
	def GetInputRoI(self, inp: Input_, slot: int) -> ImageDomain_:
		...
	def GetInputTime(self, inp: Input_, slot: int) -> TimeStamp_:
		...
	def GetOp(self) -> Operator_:
		...
	def GetOutputData(self, out: Output_) -> Parameter_:
		...
	def GetOutputDataValid(self, out: Output_) -> TimeExtent_:
		...
	def GetPending(self) -> int:
		...
	def GetPri(self) -> int:
		...
	def GetRoI(self) -> ImageDomain_:
		...
	def header_text(self) -> None:
		...
	def GetTime(self) -> float:
		...
	def IsCompleted(self) -> bool:
		...
	def IsFailed(self) -> bool:
		...
	def IsInputCurrent(self, inp: Input_, slot: int) -> bool:
		...
	def IsInputSet(self, inp: Input_, slot: int) -> bool:
		...
	def IsInteractive(self) -> bool:
		...
	def IsIntermediate(self) -> bool:
		...
	def IsNoCache(self) -> bool:
		...
	def SetOp(self, op: Operator_) -> bool:
		...
	def IsNoMotionBlur(self) -> bool:
		...
	def SetOutputCurrent(self, out: Output_, current: bool) -> bool:
		...
	def IsNoPreviewResize(self) -> bool:
		...
	def SetOutputData(self, out: Output_, param: Parameter_, te: TimeExtent_) -> bool:
		...
	def IsOutputCurrent(self, out: Output_) -> bool:
		...
	def SetPri(self, pri: int, pending: int) -> None:
		...
	def IsOutputSet(self, out: Output_) -> bool:
		...
	def IsPending(self) -> bool:
		...
	def SetReqAttrs(self, tags: TagList_) -> None:
		...
	def IsPlayback(self) -> bool:
		...
	def SetReqFlags(self, flags: int) -> None:
		...
	def IsPreCalc(self) -> bool:
		...
	def Unlock(self) -> None:
		...
	def IsPreview(self) -> bool:
		...
	def UnlockInputData(self, inp: Input_, slot: int) -> None:
		...
	def IsProcessing(self) -> bool:
		...
	def UnlockOutputData(self, out: Output_) -> None:
		...
	def IsQuick(self) -> bool:
		...
	def info_text(self) -> None:
		...
	def IsRemote(self) -> bool:
		...
	def IsSecondaryTime(self) -> bool:
		...
	def IsSerialised(self) -> bool:
		...
	def IsStampOnly(self) -> bool:
		...
	def LockInputData(self, inp: Input_, slot: int) -> None:
		...
	def IsQuiet(self) -> bool:
		...
	def LockOutputData(self, out: Output_) -> None:
		...
	def SetInputTime(self, inp: Input_, t: TimeStamp_, slot: int) -> bool:
		...

Request = Request_