class ScriptServer_:

	#---Methods---#
	def FindHost(self) -> None:
		...
	def NotifyHosts(self) -> None:
		...
	def Connect(self) -> None:
		...
	def AddHost(self) -> None:
		...
	def header_text(self) -> None:
		...
	def StartHost(self) -> None:
		...
	def GetHostList(self) -> None:
		...
	def RemoveHost(self) -> None:
		...

ScriptServer = ScriptServer_