from RefObject import RefObject_
from _non_existing import Tag_, void_


class TagList_:

	#---Methods---#
	def _Set_int32(self, tag: Tag_, val: int, addnew: bool) -> None:
		...
	def _Set_uint32(self, tag: Tag_, val: int, addnew: bool) -> None:
		...
	def _Set_float64(self, tag: Tag_, val: float, addnew: bool) -> None:
		...
	def _Set_String(self, tag: Tag_, val: str, addnew: bool) -> None:
		...
	def _Set_ID(self, tag: Tag_, val: str, addnew: bool) -> None:
		...
	def _Set_Ptr(self, tag: Tag_, val: void_, addnew: bool) -> None:
		...
	def _Set_PtrRaw(self, tag: Tag_, val: void_, addnew: bool) -> None:
		...
	def _Set_Object(self, tag: Tag_, val: RefObject_, addnew: bool) -> None:
		...
	def _Set_TagList(self, tag: Tag_, val: TagList_, addnew: bool) -> None:
		...
	def _Get_ID(self, tag: Tag_, def_: str) -> str:
		...
	def _Get_String(self, tag: Tag_, def_: str) -> str:
		...
	def info_text(self) -> None:
		...
	def TagList(self) -> TagList_:
		"""
		TagList constructor
		"""
		...
	def _Get_float64(self, tag: Tag_, def_: float) -> float:
		...
	def _Get_Ptr(self, tag: Tag_, def_: void_) -> None:
		...
	def _Get_Object(self, tag: Tag_, def_: RefObject_) -> RefObject_:
		...
	def _Get_TagList(self, tag: Tag_, def_: TagList_) -> TagList_:
		...
	def _Get_int32(self, tag: Tag_, def_: int) -> int:
		...
	def header_text(self) -> None:
		...
	def _Get_uint32(self, tag: Tag_, def_: int) -> int:
		...

TagList = TagList_